app = 'readerbear-discord-bot'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  protocol = "tcp"

  auto_stop_machines = false
  auto_start_machines = false
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
